# Generated by Django 4.2.3 on 2023-09-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_url', models.URLField()),
                ('shortened_url', models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
